language: php

# Workaround for fixing that Selenium server is not running and therefore Behat tests not working
sudo: required
# ORIGINAL:
# sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
# Workaround for fixing that Java could not be downloaded from Oracle website.
      - openjdk-8-jre-headless
# ORIGINAL:
#     - oracle-java8-installer
#     - oracle-java8-set-default

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.0
 - 7.1

env:
 global:
  - MOODLE_BRANCH=MOODLE_36_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --dump
